// Bridgeport, CT social services resources — compiled via web research April 2026
// Covers all 12 categories: housing, food, cash, harm-reduction, healthcare,
// mental-health, employment, childcare, legal, transportation, utilities, immigration

export const coreResources = [
  // ===== HOUSING =====
  {
    name: 'Bridgeport Rescue Mission - Men\'s Emergency Shelter',
    organization: 'Bridgeport Rescue Mission',
    description: 'Emergency shelter for single adult men experiencing homelessness. Provides safe beds, hot meals, showers, clean clothing, healthcare through Sage Healthcare partnership, and case management to promote independent living.',
    categories: ['housing'],
    address: '725 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 333-4087',
    website: 'https://bridgeportrescuemission.org',
    hours: '24/7 shelter; Office hours vary',
    eligibility: { housingStatus: ['homeless'], populations: ['men'] },
    howToApply: 'Walk in or call for intake. No appointment needed.',
    source: 'web-research'
  },
  {
    name: 'Bridgeport Rescue Mission - Women\'s Emergency Shelter',
    organization: 'Bridgeport Rescue Mission',
    description: 'Emergency shelter for single women experiencing homelessness. Offers safe beds, hot meals, showers, clean clothing, and supportive services to help women stabilize.',
    categories: ['housing'],
    address: '725 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 333-9143',
    website: 'https://bridgeportrescuemission.org',
    hours: '24/7 shelter',
    eligibility: { housingStatus: ['homeless'], populations: ['women'] },
    howToApply: 'Walk in or call for intake.',
    source: 'web-research'
  },
  {
    name: 'Prospect House Emergency Shelter',
    organization: 'Recovery Network of Programs',
    description: 'Emergency shelter for adults aged 18+ experiencing homelessness. 32-bed shelter providing meals, referrals to health and social services, and comprehensive case management. Intake available 24/7.',
    categories: ['housing'],
    address: '392 Prospect Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 576-9041',
    website: 'https://recovery-programs.org/program/prospect-house/',
    hours: '24/7 intake',
    eligibility: { housingStatus: ['homeless'], ageMin: 18 },
    howToApply: 'Contact the Coordinated Access Network (CAN) by dialing 211.',
    source: 'web-research'
  },
  {
    name: 'Alpha Community Services YMCA - Families in Transition Emergency Shelter',
    organization: 'Central Connecticut Coast YMCA',
    description: 'Largest emergency shelter program for families in Connecticut. Families live in the shelter for 60-90 days while receiving case management, meals (lunch, dinner, cold breakfast), and connections to permanent housing.',
    categories: ['housing'],
    address: '309 Brooks Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: null,
    website: 'https://cccymca.org/locations/alpha/emergency-shelter/',
    hours: '24/7 shelter',
    eligibility: { housingStatus: ['homeless'], populations: ['families'] },
    howToApply: 'Call 211 to initiate service and get scheduled for a CAN Navigator assessment.',
    source: 'web-research'
  },
  {
    name: 'Park City Communities (Bridgeport Housing Authority)',
    organization: 'Park City Communities',
    description: 'Public housing authority managing nearly 2,600 public housing units and 2,800 Section 8 Housing Choice Vouchers. Provides affordable, safe housing to low-income individuals, families, the elderly, and disabled.',
    categories: ['housing'],
    address: '150 Highland Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 337-8900',
    website: 'https://www.parkcitycommunities.org',
    hours: 'Mon-Fri 8:30am-4:30pm',
    eligibility: { incomeLimitPctFpl: 80 },
    howToApply: 'Apply online at parkcitycommunities.org or visit the office. Check cthcvp.org for open waitlists.',
    source: 'web-research'
  },
  {
    name: 'Homes for the Brave',
    organization: 'Homes for the Brave',
    description: 'Transitional housing and supportive services for veterans experiencing or at risk of homelessness. Provides case management, employment assistance, and pathways to permanent housing.',
    categories: ['housing'],
    address: '655 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 338-0669',
    website: 'https://homesforthebrave.org',
    hours: 'Mon-Fri 9am-5pm',
    eligibility: { populations: ['veterans'], housingStatus: ['homeless', 'at_risk'] },
    howToApply: 'Call or visit the Tony Cinquanta Veterans Service Center at (203) 275-0600.',
    source: 'web-research'
  },
  {
    name: 'Habitat for Humanity of Coastal Fairfield County',
    organization: 'Habitat for Humanity of Coastal Fairfield County',
    description: 'Builds affordable homes for ownership by low-income families. Partner families contribute 200-500 hours of sweat equity and repay an interest-free mortgage. Over 200 homes built since 1985.',
    categories: ['housing'],
    address: '1470 Barnum Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06610',
    phone: null,
    website: 'https://habitatcfc.org',
    hours: 'Mon-Fri 9am-5pm',
    eligibility: { incomeLimitPctFpl: 80 },
    howToApply: 'Apply through the Homeownership Program on their website. Must demonstrate need, willingness to partner, and ability to repay mortgage.',
    source: 'web-research'
  },
  {
    name: 'Bridgeport Relocation & Housing Hardship Program',
    organization: 'City of Bridgeport Health & Social Services',
    description: 'Emergency assistance for individuals who have received an eviction notice or are encountering hardship cases that may lead to eviction. Helps with relocation and housing stabilization.',
    categories: ['housing', 'cash'],
    address: '752 East Main Street, Room 180',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 576-7680',
    website: 'https://www.bridgeportct.gov/government/departments/health-social-services/social-services/shelters',
    hours: 'Mon-Fri 8:30am-5pm',
    eligibility: { residencyRequired: true },
    howToApply: 'Call (203) 576-7680 for intake and assessment.',
    source: 'web-research'
  },

  // ===== FOOD =====
  {
    name: 'Bridgeport Rescue Mission Food Pantry',
    organization: 'Bridgeport Rescue Mission',
    description: 'Food pantry stocked with fresh produce, dry goods, meat, and dairy items. Also serves hot meals: breakfast Mon/Wed/Fri 9:30-10:30am, lunch Tue/Thu 2-3pm.',
    categories: ['food'],
    address: '725 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 333-4087',
    website: 'https://bridgeportrescuemission.org/get-help/',
    hours: 'Pantry: Mon/Wed/Fri 10am-12pm & 1-3pm; Hot meals: Breakfast M/W/F 9:30-10:30am, Lunch Tu/Th 2-3pm',
    eligibility: { residencyRequired: false },
    howToApply: 'Walk in during pantry hours. CT residents need ID; sign up day of pickup.',
    source: 'web-research'
  },
  {
    name: 'Thomas Merton Center',
    organization: 'Catholic Charities of Fairfield County',
    description: 'One of Bridgeport\'s largest food providers. Guests select groceries with dignity in a grocery store setting. Provides 5 days of nutritious meals each week.',
    categories: ['food'],
    address: '43 Madison Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 367-9036',
    website: 'https://www.ccfairfield.org/project/thomas-merton-center/',
    hours: 'Tue/Wed 10am-1pm, Fri 11:30am-1:30pm',
    eligibility: { residencyRequired: true },
    howToApply: 'Walk in during hours. Serves zip codes 06604, 06605, 06606.',
    source: 'web-research'
  },
  {
    name: 'Salvation Army - Bridgeport Corps Food Pantry',
    organization: 'Salvation Army',
    description: 'Food pantry and emergency food assistance. Also provides other social services including clothing and emergency financial assistance.',
    categories: ['food', 'cash'],
    address: '30 Elm Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 334-0995',
    website: 'https://easternusa.salvationarmy.org/southern-new-england/bridgeport/',
    hours: 'Pantry: Mon/Tue/Thu/Fri 10am-1pm; Office: Mon-Fri 9am-4pm',
    eligibility: {},
    howToApply: 'Walk in during pantry hours. Case worker interview and payment receipts required.',
    source: 'web-research'
  },
  {
    name: 'nOURish Bridgeport',
    organization: 'nOURish Bridgeport Inc.',
    description: 'Community organization providing food pantry, soup kitchen hot meals, baby supplies (diapers, wipes, formula), hydroponic farm fresh produce, and English language classes.',
    categories: ['food', 'immigration'],
    address: '2200 North Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 335-3107',
    website: 'https://www.nourishbpt.org',
    hours: 'Pantry: Wed 2-6pm; Soup Kitchen: Thu 6-7pm; Office: Tue-Fri 9am-5pm',
    eligibility: {},
    howToApply: 'Walk in during program hours. No appointment needed for food pantry or soup kitchen.',
    source: 'web-research'
  },
  {
    name: 'Calvary Saint George\'s Food Pantry & Soup Kitchen',
    organization: 'Calvary Saint George\'s Church',
    description: 'Food pantry serving the Bridgeport community with groceries and meals.',
    categories: ['food'],
    address: '755 Clinton Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 333-5116',
    website: null,
    hours: 'Tue/Thu 9:30-11:30am',
    eligibility: {},
    howToApply: 'Walk in with picture ID.',
    source: 'web-research'
  },
  {
    name: 'Kings Pantry',
    organization: 'Kings Pantry',
    description: 'Community food pantry serving the Greater Bridgeport area with groceries and food assistance.',
    categories: ['food'],
    address: '30 Florence Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06607',
    phone: '(203) 576-0522',
    website: null,
    hours: 'Mon-Fri 10:30am-1:30pm',
    eligibility: {},
    howToApply: 'Walk in during hours. Greater Bridgeport residents.',
    source: 'web-research'
  },
  {
    name: 'Gospel Mission Community Fridge & Pantry',
    organization: 'Gospel Mission',
    description: 'Community fridge and pantry available 24/7. External pantry operates on a "take what you need, leave what you can" basis — no ID or appointment required.',
    categories: ['food'],
    address: '219 James Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(877) 327-7925',
    website: null,
    hours: '24/7 (external pantry)',
    eligibility: {},
    howToApply: 'No application needed. Walk up anytime.',
    source: 'web-research'
  },
  {
    name: 'Saint Luke/Saint Paul\'s Episcopal Church Food Center',
    organization: 'Saint Luke/Saint Paul\'s Episcopal Church',
    description: 'Food center providing groceries to community members. Operates on an agency referral basis.',
    categories: ['food'],
    address: '598 Kossuth Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 367-7009',
    website: null,
    hours: 'Mon-Thu 10am-12:30pm',
    eligibility: {},
    howToApply: 'Agency referral required.',
    source: 'web-research'
  },
  {
    name: 'Park City Initiative Food Pantry',
    organization: 'Park City Initiative',
    description: 'Food pantry serving Bridgeport residents with groceries and food assistance.',
    categories: ['food'],
    address: '4 Worth Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 873-0260',
    website: null,
    hours: 'Tue 10am-2pm, Wed 12-4pm, Thu 1-6pm',
    eligibility: { residencyRequired: true },
    howToApply: 'Walk in with proof of residency.',
    source: 'web-research'
  },
  {
    name: 'Black Rock Food Pantry',
    organization: 'Black Rock Food Pantry',
    description: 'Walk-in community food pantry in the Black Rock neighborhood. No appointment needed.',
    categories: ['food'],
    address: '15 Princeton Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 610-1222',
    website: null,
    hours: 'Saturday 9-11:30am (walk-in)',
    eligibility: {},
    howToApply: 'Walk in on Saturdays. No appointment needed.',
    source: 'web-research'
  },
  {
    name: 'Connecticut Foodshare',
    organization: 'Connecticut Foodshare',
    description: 'Statewide food bank network distributing food to pantries and meal programs across Connecticut including Bridgeport. Use their website to find the nearest distribution point.',
    categories: ['food'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: '(203) 469-5000',
    website: 'https://www.ctfoodshare.org',
    hours: 'Varies by distribution site',
    eligibility: {},
    howToApply: 'Visit ctfoodshare.org to find your nearest food distribution site.',
    source: 'web-research'
  },

  // ===== CASH ASSISTANCE =====
  {
    name: 'CT Department of Social Services - Bridgeport Office',
    organization: 'Connecticut Department of Social Services',
    description: 'State office administering SNAP (food stamps), Temporary Family Assistance (TFA/TANF), Medicaid/HUSKY Health, and other public benefits for low-income individuals and families.',
    categories: ['cash', 'food', 'healthcare'],
    address: '925 Housatonic Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06606',
    phone: '(855) 626-6632',
    website: 'https://portal.ct.gov/dss',
    hours: 'Mon/Tue/Fri 8:30am-4:30pm; Wed/Thu 8:30am-12pm',
    eligibility: {},
    howToApply: 'Apply online at portal.ct.gov/DSS, call 1-855-626-6632, or visit the office in person.',
    source: 'web-research'
  },
  {
    name: 'Temporary Family Assistance (TFA/TANF) - Bridgeport',
    organization: 'Connecticut Department of Social Services',
    description: 'Cash assistance for families with dependent children under 18 to help pay for basic needs while in school, job training, or experiencing hardship. Includes emergency housing assistance for up to 60 days if housing is lost.',
    categories: ['cash'],
    address: '925 Housatonic Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06606',
    phone: '(855) 626-6632',
    website: 'https://portal.ct.gov/dss/economic-security/economic-security---financial-assistance/',
    hours: 'Mon/Tue/Fri 8:30am-4:30pm; Wed/Thu 8:30am-12pm',
    eligibility: { incomeLimitPctFpl: 55, populations: ['families'] },
    howToApply: 'Apply online at portal.ct.gov/DSS, by phone at 1-855-626-6632, or in person at the Bridgeport DSS office.',
    source: 'web-research'
  },
  {
    name: 'Alliance for Community Empowerment - Emergency Assistance',
    organization: 'Alliance for Community Empowerment',
    description: 'Community action agency providing emergency financial assistance for rent, utilities, and other basic needs. Serves over 35,000 individuals annually across the Greater Bridgeport area.',
    categories: ['cash', 'utilities'],
    address: '1070 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 366-8241',
    website: 'https://alliancect.org',
    hours: 'Mon-Fri 8:30am-5pm',
    eligibility: { residencyRequired: true },
    howToApply: 'Call or visit the office for intake and assessment.',
    source: 'web-research'
  },

  // ===== HARM REDUCTION =====
  {
    name: 'Liberation Programs - Bridgeport Outpatient',
    organization: 'Liberation Programs',
    description: 'Outpatient substance use treatment using a harm reduction approach. Offers intensive outpatient (IOP) and medication-assisted treatment (MAT) including Suboxone, Vivitrol, and methadone. Carries Narcan for overdose reversal. Individual, group, and family counseling available.',
    categories: ['harm-reduction', 'mental-health'],
    address: '399 Mill Hill Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06610',
    phone: '(203) 391-7913',
    website: 'https://www.liberationprograms.org',
    hours: 'Mon-Sat (6 days/week)',
    eligibility: {},
    howToApply: 'Call for intake. Services not denied due to inability to pay; sliding scale fees available.',
    source: 'web-research'
  },
  {
    name: 'Recovery Network of Programs - Recovery Counseling Services',
    organization: 'Recovery Network of Programs',
    description: 'Outpatient substance use treatment and recovery counseling. Offers recovery coaching, mentoring/peer support, naloxone and overdose education, transitional services, and discharge planning.',
    categories: ['harm-reduction', 'mental-health'],
    address: '1549 Fairfield Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(475) 251-7985',
    website: 'https://recovery-programs.org',
    hours: 'Mon-Thu 8:30am-8:30pm; Fri 8:30am-5pm',
    eligibility: { ageMin: 18 },
    howToApply: 'Call for intake assessment.',
    source: 'web-research'
  },
  {
    name: 'Recovery Network of Programs - First Step',
    organization: 'Recovery Network of Programs',
    description: 'Inpatient detox and early recovery program for adults with substance use disorders. Provides medical stabilization and transition planning to ongoing treatment.',
    categories: ['harm-reduction'],
    address: '425 Grant Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06610',
    phone: '(475) 251-7985',
    website: 'https://recovery-programs.org/program/first-step/',
    hours: 'Mon-Fri 6am-7pm; Sat 6:30-10:30am',
    eligibility: { ageMin: 18 },
    howToApply: 'Call for intake. May require referral.',
    source: 'web-research'
  },
  {
    name: 'CASA Inc. (Chemical Abuse Services Agency)',
    organization: 'CASA Inc.',
    description: 'Bilingual (English/Spanish) substance abuse treatment including residential recovery house (14-bed, men 18+), outpatient treatment (Project Courage), psychiatric services, auricular acupuncture, STD testing, and relapse prevention. Also provides supportive housing.',
    categories: ['harm-reduction', 'housing'],
    address: '690 Arctic Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 339-4112',
    website: 'https://www.casaincct.org',
    hours: 'Call for hours',
    eligibility: { ageMin: 18 },
    howToApply: 'Call for intake assessment. Bilingual services available.',
    source: 'web-research'
  },
  {
    name: 'Advancing CT Together (ACT) - Harm Reduction',
    organization: 'Advancing CT Together',
    description: 'Statewide harm reduction services including syringe service program (SSP), naloxone/Narcan distribution, overdose prevention education, HIV/Hepatitis C screening, and safer sex supplies. Non-judgmental approach to drug user health.',
    categories: ['harm-reduction'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: null,
    website: 'https://act-ct.org/harm-reduction.html',
    hours: 'Varies by service; contact for schedule',
    eligibility: {},
    howToApply: 'Contact via website or email actoutreach@act-ct.org for Bridgeport service locations and schedules.',
    source: 'web-research'
  },

  // ===== HEALTHCARE =====
  {
    name: 'Southwest Community Health Center',
    organization: 'Southwest Community Health Center',
    description: 'Federally Qualified Health Center (FQHC) providing comprehensive medical, dental, and behavioral health services to uninsured and low-income individuals. Services include internal medicine, pediatrics, OB/GYN, dental, mental health, nutrition, podiatry, and WIC.',
    categories: ['healthcare'],
    address: '46 Albion Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 330-6000',
    website: 'https://swchc.org',
    hours: 'Mon-Fri; call for specific hours',
    eligibility: { incomeLimitPctFpl: 200 },
    howToApply: 'Call to schedule an appointment. Sliding fee discount for uninsured patients below 200% FPL.',
    source: 'web-research'
  },
  {
    name: 'Optimus Health Care',
    organization: 'Optimus Health Care Inc.',
    description: 'FQHC operating 11 primary care sites, 6 school-based health centers, 3 homeless health centers, and a WIC program. Provides adult primary care, pediatrics, women\'s health, dental, and behavioral health services.',
    categories: ['healthcare'],
    address: '982 East Main Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 696-3260',
    website: 'https://optimushealthcare.org',
    hours: 'Mon-Fri 8am-5pm',
    eligibility: {},
    howToApply: 'Call to schedule an appointment. Accepts Medicaid, Medicare, and offers sliding scale.',
    source: 'web-research'
  },
  {
    name: 'Fred Weisman Americares Free Clinic of Bridgeport',
    organization: 'Americares Free Clinics',
    description: 'Free medical clinic for uninsured adults. Provides primary care, chronic disease management, and health screenings at no cost to eligible patients.',
    categories: ['healthcare'],
    address: '115 Highland Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 333-9175',
    website: 'https://americaresfreeclinics.org/our-clinics/bridgeport/',
    hours: 'Tue 9am-4:30pm; Thu 12:30-4:30pm; Sat 8:30am-12:30pm',
    eligibility: { incomeLimitPctFpl: 250, ageMin: 18, insuranceRequired: false },
    howToApply: 'Call to schedule an appointment and verify eligibility. Must be uninsured (no Medicaid, Medicare, or VA), 18+, and reside in service area.',
    source: 'web-research'
  },
  {
    name: 'Park City Primary Care Center',
    organization: 'Optimus Health Care',
    description: 'Community health center providing primary care, dental care, and behavioral health services on a sliding fee scale for low-income and uninsured residents.',
    categories: ['healthcare'],
    address: '64 Black Rock Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 579-5000',
    website: 'https://optimushealthcare.org',
    hours: 'Mon-Fri; call for hours',
    eligibility: {},
    howToApply: 'Call to schedule. Sliding fee scale available.',
    source: 'web-research'
  },
  {
    name: 'HUSKY Health / Medicaid Enrollment',
    organization: 'Access Health CT',
    description: 'Connecticut\'s Medicaid program (HUSKY Health) provides free or low-cost health coverage including medical, dental, and behavioral health. HUSKY A covers children/parents, HUSKY B covers children in higher-income households, HUSKY D covers adults without dependents.',
    categories: ['healthcare'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: '(855) 805-4325',
    website: 'https://www.accesshealthct.com',
    hours: 'Phone: Mon-Fri 8am-5pm',
    eligibility: {},
    howToApply: 'Apply online at accesshealthct.com, call 1-855-805-4325, or visit the Bridgeport DSS office at 925 Housatonic Ave.',
    source: 'web-research'
  },
  {
    name: 'Bridgeport Community Health Center',
    organization: 'Bridgeport Community Health Center',
    description: 'Community health center providing primary care, preventive services, and health education on a sliding fee scale.',
    categories: ['healthcare'],
    address: '982 East Main Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 696-3260',
    website: null,
    hours: 'Mon-Fri 8am-5pm',
    eligibility: {},
    howToApply: 'Call to schedule an appointment.',
    source: 'web-research'
  },
  {
    name: 'Ralphola Taylor Community Health Center',
    organization: 'Southwest Community Health Center',
    description: 'Satellite community health center providing primary medical care, dental services, and behavioral health on a sliding scale basis.',
    categories: ['healthcare'],
    address: '790 Central Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06607',
    phone: '(203) 332-4567',
    website: 'https://swchc.org',
    hours: 'Mon-Fri; call for hours',
    eligibility: {},
    howToApply: 'Call to schedule an appointment.',
    source: 'web-research'
  },

  // ===== MENTAL HEALTH =====
  {
    name: 'Greater Bridgeport Community Mental Health Center (GBCMHC)',
    organization: 'CT Dept. of Mental Health & Addiction Services (DMHAS)',
    description: 'State-operated facility providing intensive psychiatric care, clinical evaluations, outreach programs, crisis intervention, medication clinic, and co-occurring treatment for adults 18+. 24-hour crisis line available.',
    categories: ['mental-health'],
    address: '1635 Central Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06610',
    phone: '(203) 551-7400',
    website: 'https://portal.ct.gov/dmhas/swcmhs/agency-files/gbcmhc',
    hours: 'Mon-Sun 8am-6pm; 24-hour crisis line: (203) 551-7507',
    eligibility: { ageMin: 18 },
    howToApply: 'Call main number or 24-hour crisis line at (203) 551-7507. Walk-ins accepted for crisis.',
    source: 'web-research'
  },
  {
    name: 'LifeBridge Community Services - Behavioral Health',
    organization: 'LifeBridge Community Services',
    description: 'Trauma-informed outpatient mental health services including dialectical behavior therapy (DBT), trauma therapy, group therapy, family psychoeducation, case management, and psychosocial rehabilitation for youth, adults, and families.',
    categories: ['mental-health'],
    address: '475 Clinton Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 368-4291',
    website: 'https://lifebridgect.org/behavioral-health-services/',
    hours: 'Mon-Fri; call for hours',
    eligibility: {},
    howToApply: 'Call for intake assessment.',
    source: 'web-research'
  },
  {
    name: 'Connecticut Renaissance - Bridgeport Outpatient',
    organization: 'Connecticut Renaissance',
    description: 'Outpatient behavioral health services for adolescents and adults with addiction and/or mental health disorders. Offers therapy, medication management, LYNC youth program, life skills training, and case management. Accepts Medicaid and sliding scale.',
    categories: ['mental-health', 'harm-reduction'],
    address: '1126 Main Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 331-1503',
    website: 'https://ctrenaissance.org',
    hours: 'Mon-Fri; call for hours',
    eligibility: {},
    howToApply: 'Call for intake. Accepts Medicaid, commercial insurance, and sliding fee scale for uninsured.',
    source: 'web-research'
  },
  {
    name: 'Bridgeport Hospital - Psychiatric Emergency & Behavioral Health',
    organization: 'Bridgeport Hospital (Yale New Haven Health)',
    description: '24-hour emergency psychiatric services for adults, adolescents, children, and seniors. Inpatient psychiatric care, crisis intervention, outpatient programs (REACH), and geriatric mental health services.',
    categories: ['mental-health'],
    address: '267 Grant Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06610',
    phone: '(203) 384-3292',
    website: 'https://www.bridgeporthospital.org/services/mental-health',
    hours: '24/7 for emergency; inpatient and outpatient hours vary',
    eligibility: {},
    howToApply: 'Go to the Emergency Department for crisis. Call (203) 384-3292 for inpatient program info or 1-888-357-2396 for referrals.',
    source: 'web-research'
  },
  {
    name: '988 Suicide & Crisis Lifeline',
    organization: 'SAMHSA',
    description: 'Free, confidential 24/7 crisis support for anyone in suicidal crisis or emotional distress. Call, text, or chat. Available in English and Spanish.',
    categories: ['mental-health'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: '988',
    website: 'https://988lifeline.org',
    hours: '24/7',
    eligibility: {},
    howToApply: 'Call or text 988. Chat at 988lifeline.org.',
    source: 'web-research'
  },

  // ===== EMPLOYMENT =====
  {
    name: 'American Job Center - Southwest Connecticut',
    organization: 'Career Resources Inc.',
    description: 'One-stop career center providing job search assistance, career coaching, resume help, job training information, educational opportunities, and access to hiring events. Free services.',
    categories: ['employment'],
    address: '2 Lafayette Square',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 333-5129',
    website: 'https://ajcswct.com',
    hours: 'Mon-Fri 8:30am-4:30pm',
    eligibility: {},
    howToApply: 'Walk in or call. Services are free and open to all job seekers.',
    source: 'web-research'
  },
  {
    name: 'The WorkPlace',
    organization: 'The WorkPlace Inc.',
    description: 'Major workforce development nonprofit offering skills training, job search assistance, job placement, and support services for youth (18-24), adults, mature workers, veterans, people with disabilities, and formerly incarcerated individuals.',
    categories: ['employment'],
    address: '1000 Lafayette Blvd, Suite 501',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 610-8500',
    website: 'https://www.workplace.org',
    hours: 'Mon-Fri 8:30am-5pm',
    eligibility: {},
    howToApply: 'Call or visit the office. Programs serve multiple populations including youth, veterans, and dislocated workers.',
    source: 'web-research'
  },
  {
    name: 'Career Resources Inc. - STRIVE Program',
    organization: 'Career Resources Inc.',
    description: 'Job training and placement for disadvantaged individuals. STRIVE offers a 3-week intensive course on job-seeking skills and work readiness, plus post-placement support. Also operates a GED Testing Center.',
    categories: ['employment'],
    address: '1000 Lafayette Boulevard',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 334-5627',
    website: 'https://careerresources.org',
    hours: 'Mon-Fri; call for program schedules',
    eligibility: {},
    howToApply: 'Call or visit to enroll in STRIVE or other workforce programs.',
    source: 'web-research'
  },
  {
    name: 'CT State Housatonic - Workforce Development & Continuing Education',
    organization: 'CT State Community College (Housatonic)',
    description: 'Short-term licensure and certificate training programs in allied healthcare, manufacturing, IT, hospitality, and more. ESL, GED prep, and adult education also available. Programs for those re-entering the workforce or acquiring new technical skills.',
    categories: ['employment'],
    address: '900 Lafayette Blvd',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 332-5057',
    website: 'https://ctstate.edu/workforce-development/wdce',
    hours: 'Mon-Fri; WDCE office at Room BH-116',
    eligibility: {},
    howToApply: 'Contact the WDCE office at (203) 332-5057 or visit in person.',
    source: 'web-research'
  },
  {
    name: 'Homes for the Brave - Veterans Service Center',
    organization: 'Homes for the Brave',
    description: 'Employment assistance, resume writing, job placement, and career coaching specifically for veterans. Also provides case management and supportive services.',
    categories: ['employment'],
    address: '1 Lafayette Circle, Suite 100',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 275-0600',
    website: 'https://homesforthebrave.org/programs/veterans-service-center/',
    hours: 'Mon-Fri; call for hours',
    eligibility: { populations: ['veterans'] },
    howToApply: 'Call or walk in. Open to veterans.',
    source: 'web-research'
  },

  // ===== CHILDCARE =====
  {
    name: 'Alliance for Community Empowerment - Head Start',
    organization: 'Alliance for Community Empowerment',
    description: 'Federal Head Start and Early Head Start programs at 13 sites across Greater Bridgeport, Trumbull, and Stratford. Full-year preschool for children 0-5 from low-income families. Part-day (9am-1:50pm, free) and full-day (7:30am-5:30pm, sliding scale) options.',
    categories: ['childcare'],
    address: '1070 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 366-8241',
    website: 'https://alliancect.org/early-learning-programs/',
    hours: 'Part-day: 9am-1:50pm; Full-day: 7:30am-5:30pm',
    eligibility: { incomeLimitPctFpl: 100, populations: ['families'] },
    howToApply: 'Call (203) 366-8241 to apply. Income eligibility based on federal poverty guidelines.',
    source: 'web-research'
  },
  {
    name: 'Care 4 Kids - CT Childcare Subsidy Program',
    organization: 'Connecticut Office of Early Childhood',
    description: 'State childcare subsidy program helping low-income families pay for childcare. Currently no waitlist in Connecticut. Co-pays capped at 7% of monthly household income.',
    categories: ['childcare'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: '(888) 214-5437',
    website: 'https://www.ctcare4kids.com',
    hours: 'Phone: Mon-Fri 8am-5pm',
    eligibility: {},
    howToApply: 'Apply online at ctcare4kids.com or call 1-888-214-KIDS.',
    source: 'web-research'
  },
  {
    name: 'Wakeman Boys & Girls Club - After School Program',
    organization: 'Wakeman Boys & Girls Club',
    description: 'After-school program for kids and teens in grades K-12. Enriching programming promoting academic success, character development, leadership, and healthy lifestyles.',
    categories: ['childcare'],
    address: '595 Madison Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 908-3381',
    website: 'https://www.wakemanclub.org/SBCASP',
    hours: 'Mon-Thu 2-6pm; Fri 2-6pm/8pm',
    eligibility: {},
    howToApply: 'Contact the club to enroll or visit wakemanclub.org.',
    source: 'web-research'
  },
  {
    name: 'Jerome Orcutt Boys & Girls Club',
    organization: 'Jerome Orcutt Boys Club & Girls Club of Bridgeport',
    description: 'After-school programming including homework help, tutoring, recreation, arts and crafts, and organized sports. Summer programs available. One of the oldest Boys & Girls Clubs in the US (founded 1887).',
    categories: ['childcare'],
    address: '102 Park Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: null,
    website: 'https://www.jeromeorcutt.org',
    hours: 'After school hours during school year; summer hours vary',
    eligibility: {},
    howToApply: 'Visit the club or website to register.',
    source: 'web-research'
  },
  {
    name: 'Mercy Learning Center - Childcare',
    organization: 'Mercy Learning Center',
    description: 'Free on-site licensed childcare for children ages 3 months to 4 years while their mothers attend literacy and education programs at the center.',
    categories: ['childcare'],
    address: '637 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 334-6699',
    website: 'https://mercylearningcenter.org',
    hours: 'Sep-Jun; hours align with class schedules',
    eligibility: { populations: ['women'] },
    howToApply: 'Childcare available to enrolled students only. Call to inquire about education programs.',
    source: 'web-research'
  },

  // ===== LEGAL =====
  {
    name: 'Connecticut Legal Services - Bridgeport Office',
    organization: 'Connecticut Legal Services (CLS)',
    description: 'Free legal services for low-income residents covering housing, family/domestic violence, health law, public benefits, employment, elder law, education, juvenile law, and immigration (VAWA, DACA, SIJ, asylum).',
    categories: ['legal', 'immigration'],
    address: '211 State Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 336-3851',
    website: 'https://ctlegal.org',
    hours: 'Mon-Fri 9am-5pm',
    eligibility: { incomeLimitPctFpl: 125 },
    howToApply: 'Call for intake. Free to eligible clients at or below 125% FPL, or age 59+.',
    source: 'web-research'
  },
  {
    name: 'CT Right to Counsel - Eviction Defense',
    organization: 'Eviction Help CT',
    description: 'Free legal representation for eligible tenants facing eviction or loss of housing subsidy in Connecticut Housing Court. Part of Connecticut\'s Right to Counsel program.',
    categories: ['legal'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: null,
    website: 'https://evictionhelpct.org',
    hours: 'Varies',
    eligibility: {},
    howToApply: 'Visit evictionhelpct.org or call Connecticut Legal Services at (203) 336-3851. File an Appearance Form (JD-CL-12) immediately upon receiving eviction notice.',
    source: 'web-research'
  },
  {
    name: 'CT Clean Slate / Expungement Assistance',
    organization: 'State of Connecticut',
    description: 'Connecticut\'s Clean Slate law provides automatic erasure of most low-level convictions after 7 years (misdemeanors) or 10 years (felonies). For cases not eligible for automatic erasure, you can apply for an Absolute Pardon through the Board of Pardons and Paroles.',
    categories: ['legal'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: '(203) 805-6643',
    website: 'https://portal.ct.gov/cleanslate',
    hours: 'Phone hours: Mon-Fri 8:30am-4:30pm',
    eligibility: {},
    howToApply: 'Visit portal.ct.gov/cleanslate to check eligibility and access erasure petitions. Call CT Board of Pardons and Paroles at (203) 805-6643 for pardon applications.',
    source: 'web-research'
  },

  // ===== TRANSPORTATION =====
  {
    name: 'Greater Bridgeport Transit (GBT)',
    organization: 'Greater Bridgeport Transit Authority',
    description: 'Public bus system serving Bridgeport and surrounding towns. Base fare $1.75; 31-day pass $45. Reduced fares (half-price) for seniors 65+, people with disabilities, and Medicare cardholders. GBT Access paratransit available for riders with disabilities.',
    categories: ['transportation'],
    address: '1 Cross Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06610',
    phone: '(203) 366-7070',
    website: 'https://gogbt.com',
    hours: 'Routes vary; see gogbt.com for schedules',
    eligibility: {},
    howToApply: 'Board any GBT bus. For reduced fare, show CT Elderly/Disabled ID card or Medicare card. For GBT Access paratransit, apply at gogbt.com.',
    source: 'web-research'
  },
  {
    name: 'Veyo - Non-Emergency Medical Transportation (NEMT)',
    organization: 'Veyo (State of CT contractor)',
    description: 'Free medical transportation for HUSKY Health (Medicaid) members who have no other way to get to medical, behavioral health, or dental appointments. Covers rides to and from appointments.',
    categories: ['transportation'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: '(855) 478-7350',
    website: 'https://ct.ridewithveyo.com',
    hours: 'Reservations: Mon-Fri 7am-6pm EST',
    eligibility: { populations: ['medicaid_members'] },
    howToApply: 'Call (855) 478-7350 with your Medicaid ID to schedule rides at least 2 business days in advance.',
    source: 'web-research'
  },
  {
    name: 'Bridgeport Veterans Affairs - VA Hospital Shuttle',
    organization: 'City of Bridgeport Veterans Affairs',
    description: 'Free shuttle service for Bridgeport veterans and their spouses to the VA Hospital in West Haven. Two round-trips daily, Monday through Friday.',
    categories: ['transportation'],
    address: '752 East Main Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 576-7680',
    website: 'https://www.bridgeportct.gov',
    hours: 'Mon-Fri; first departure 9:45am from 752 East Main St.',
    eligibility: { populations: ['veterans'] },
    howToApply: 'Visit the Veterans Affairs Office at 752 East Main Street to sign up for the shuttle.',
    source: 'web-research'
  },

  // ===== UTILITIES =====
  {
    name: 'CT Energy Assistance Program (CEAP) - Bridgeport',
    organization: 'Alliance for Community Empowerment',
    description: 'Help paying winter heating bills. Benefits paid directly to utility company or fuel vendor. Recipients may also qualify for payment matching plans, shut-off protection, and heating equipment repair/replacement.',
    categories: ['utilities'],
    address: '1070 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 366-8241 ext. 3991',
    website: 'https://portal.ct.gov/heatinghelp',
    hours: 'Mon-Fri 8:30am-5pm (seasonal program)',
    eligibility: {},
    howToApply: 'Call (203) 366-8241 ext. 3991 or visit the office. Income must be at or below 60% of state median income.',
    source: 'web-research'
  },
  {
    name: 'Home Energy Solutions - Income Eligible (HES-IE)',
    organization: 'Energize CT / Eversource',
    description: 'Free weatherization services for income-eligible households including insulation, air sealing, duct sealing, energy-efficient lighting, and appliance upgrades. Expert energy diagnostics and recommendations.',
    categories: ['utilities'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: '(877) 947-3873',
    website: 'https://energizect.com',
    hours: 'Phone: Mon-Fri 8am-5pm',
    eligibility: {},
    howToApply: 'Call 1-877-WISE-USE or visit energizect.com. Income eligibility based on household size.',
    source: 'web-research'
  },
  {
    name: 'Operation Fuel',
    organization: 'Operation Fuel',
    description: 'Year-round energy assistance for households that fall through the gaps of other programs. Helps pay heating and electric bills for working families and individuals who earn too much for CEAP but still struggle.',
    categories: ['utilities'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: '(860) 243-2345',
    website: 'https://operationfuel.org',
    hours: 'Phone: Mon-Fri 9am-5pm',
    eligibility: {},
    howToApply: 'Call 2-1-1 for a referral to your local Operation Fuel provider.',
    source: 'web-research'
  },

  // ===== IMMIGRATION =====
  {
    name: 'Connecticut Institute for Refugees and Immigrants (CIRI) - Bridgeport',
    organization: 'CIRI',
    description: 'Comprehensive immigration services since 1918. BIA-recognized provider of asylum applications, U-visas, SIJS, family petitions, naturalization/citizenship, deportation defense, employment authorization, and citizenship preparation classes. Also provides refugee resettlement, workforce readiness, job placement, and financial literacy.',
    categories: ['immigration', 'legal'],
    address: '670 Clinton Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 336-0141',
    website: 'https://cirict.org',
    hours: 'Mon-Fri 9am-5pm',
    eligibility: {},
    howToApply: 'Call or visit the office. Email immigration@cirict.org for citizenship class info.',
    source: 'web-research'
  },
  {
    name: 'Bridgeport Adult Education - ESL & Citizenship Classes',
    organization: 'Bridgeport Public Schools',
    description: 'Free English as a Second Language (ESL) classes from introductory to advanced levels. Also offers citizenship preparation courses covering US History, Government, and Civics for the USCIS exam. GED and adult basic education also available.',
    categories: ['immigration', 'employment'],
    address: '1 Lincoln Boulevard (Central High School)',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06606',
    phone: '(203) 275-1509',
    website: 'https://www.bridgeportedu.net/academics/adult-education/esl-program',
    hours: 'Day classes at 418 Kossuth St; Evening classes at Central High School',
    eligibility: {},
    howToApply: 'Call (203) 275-1509 to register. All classes are free.',
    source: 'web-research'
  },
  {
    name: 'nOURish Bridgeport - English Language & Citizenship Classes',
    organization: 'nOURish Bridgeport Inc.',
    description: 'English language classes at beginner, intermediate, and advanced levels plus citizenship preparation, personal finance, computer literacy, and reading classes. Community-based program helping newest neighbors adapt to American life.',
    categories: ['immigration'],
    address: '2200 North Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 335-3107',
    website: 'https://www.nourishbpt.org/english',
    hours: 'Office: Tue-Fri 9am-5pm; class schedules vary',
    eligibility: {},
    howToApply: 'Call or visit nourishbpt.org/english for class schedule and enrollment.',
    source: 'web-research'
  },
  {
    name: 'CT Refugee Assistance Program',
    organization: 'CT Dept. of Social Services / CIRI',
    description: 'State-funded refugee resettlement services including case management, employment assistance, and supportive services for newly arrived refugees. Administered through CIRI in Bridgeport.',
    categories: ['immigration'],
    address: '670 Clinton Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 336-0141',
    website: 'https://portal.ct.gov/dss/archived-folder/refugee-assistance-program',
    hours: 'Mon-Fri 9am-5pm',
    eligibility: { populations: ['refugees'] },
    howToApply: 'Contact CIRI at (203) 336-0141 for intake.',
    source: 'web-research'
  },
  {
    name: 'Mercy Learning Center - Women\'s Literacy & ESL',
    organization: 'Mercy Learning Center',
    description: 'Free literacy and life skills education for low-income women. Full-time and part-time ESL, Adult Basic Education, and GED programs. On-site childcare (ages 3mo-4yr) available. Holistic, supportive learning environment.',
    categories: ['immigration', 'employment'],
    address: '637 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 334-6699',
    website: 'https://mercylearningcenter.org',
    hours: 'Sep-Jun; Mon-Fri; call for class schedule',
    eligibility: { populations: ['women'] },
    howToApply: 'Call (203) 334-6699 to apply. All programs and services are free.',
    source: 'web-research'
  },

  // ===== 211 / GENERAL NAVIGATION =====
  {
    name: '211 Connecticut',
    organization: 'United Way of Connecticut',
    description: 'Statewide information and referral service connecting residents with social services including housing, food, healthcare, childcare, employment, and more. Available 24/7 by phone. Also coordinates the Coordinated Access Network (CAN) for homeless services.',
    categories: ['housing', 'food', 'cash', 'healthcare', 'mental-health'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: '211',
    website: 'https://www.211ct.org',
    hours: '24/7 by phone',
    eligibility: {},
    howToApply: 'Dial 2-1-1 or visit 211ct.org. Available in multiple languages.',
    source: 'web-research'
  },
  {
    name: 'Bridgeport Rescue Mission - Resource Center',
    organization: 'Bridgeport Rescue Mission',
    description: 'Resource center assisting with utility payment applications, housing applications, identification documentation, and social service connections. Also provides free medical, dental, and mental health care through Sage Healthcare partnership.',
    categories: ['healthcare', 'housing', 'utilities'],
    address: '725 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 916-0862',
    website: 'https://bridgeportrescuemission.org',
    hours: 'Call for hours',
    eligibility: {},
    howToApply: 'Call or walk in.',
    source: 'web-research'
  },
]


export const categorySeeds = [
  { name: 'Housing', slug: 'housing', icon: '🏠', displayOrder: 1 },
  { name: 'Food', slug: 'food', icon: '🍎', displayOrder: 2 },
  { name: 'Cash Assistance', slug: 'cash', icon: '💵', displayOrder: 3 },
  { name: 'Harm Reduction', slug: 'harm-reduction', icon: '💊', displayOrder: 4 },
  { name: 'Healthcare', slug: 'healthcare', icon: '🏥', displayOrder: 5 },
  { name: 'Mental Health', slug: 'mental-health', icon: '🧠', displayOrder: 6 },
  { name: 'Employment', slug: 'employment', icon: '💼', displayOrder: 7 },
  { name: 'Childcare', slug: 'childcare', icon: '👶', displayOrder: 8 },
  { name: 'Legal Aid', slug: 'legal', icon: '⚖️', displayOrder: 9 },
  { name: 'Transportation', slug: 'transportation', icon: '🚌', displayOrder: 10 },
  { name: 'Utilities', slug: 'utilities', icon: '💡', displayOrder: 11 },
  { name: 'Immigration', slug: 'immigration', icon: '📄', displayOrder: 12 },
]
