// Bridgeport, CT social services resources — EXPANSION batch
// Compiled via web research April 2026
// 37 additional resources covering churches with food pantries, sober living,
// domestic violence, youth services, senior services, dental/vision, and more

export const expansionResources = [

  // ===== FOOD — CHURCH FOOD PANTRIES =====
  {
    name: 'Blessed Sacrament Church Food Pantry',
    organization: 'Church of the Blessed Sacrament',
    description: 'Parish food pantry serving over 300 registered families. Sourced from CT Food Bank and supplemented by donations from other parishes. Open every Thursday except the first Thursday of the month.',
    categories: ['food'],
    address: '275 Union Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06607',
    phone: '(203) 332-5658',
    website: 'https://www.blessedsacramentbpt.org/food-pantry',
    hours: 'Thu 7:30am-10am (except 1st Thu of month)',
    eligibility: {},
    howToApply: 'Walk in during pantry hours. Bring picture ID.',
    source: 'web-research'
  },
  {
    name: 'Summerfield UMC - Light on the Hill Food Pantry',
    organization: 'Summerfield United Methodist Church',
    description: 'Church-based food pantry operating since 2005. Distribution on the 2nd and 4th Friday of each month. Serves families in the North End / North Bridgeport neighborhood.',
    categories: ['food'],
    address: '110 Clermont Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06610',
    phone: '(203) 367-8783',
    website: null,
    hours: '2nd & 4th Fri; call Mon-Wed 9:30am-12:30pm for appointment',
    eligibility: {},
    howToApply: 'Call (203) 367-8783 Mon-Wed 9:30am-12:30pm to schedule pickup. Bring picture ID, proof of family size, and birth certificate/SSN for household members.',
    source: 'web-research'
  },
  {
    name: 'Salem Lutheran Church Food Pantry',
    organization: 'Salem Lutheran Church',
    description: 'Church-based food pantry in the North End of Bridgeport, distributing groceries to community members in need on a biweekly schedule.',
    categories: ['food'],
    address: '3160 Park Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 336-3300',
    website: 'https://salembridgeport.org',
    hours: '2nd & 4th Thu 5pm-6:30pm',
    eligibility: {},
    howToApply: 'Walk in during pantry hours. Call ahead to confirm schedule as hours may change.',
    source: 'web-research'
  },
  {
    name: 'St. Charles Borromeo Food Pantry',
    organization: 'Saint Charles Borromeo & Saint George Parish',
    description: 'Parish food pantry serving the East Side Bridgeport community with groceries and food assistance on a weekly basis.',
    categories: ['food'],
    address: '391 Ogden Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 333-2147',
    website: 'https://www.stcharlesbridgeport.org/food-pantry',
    hours: 'Fri 9am-11am',
    eligibility: {},
    howToApply: 'Walk in during pantry hours with picture ID.',
    source: 'web-research'
  },

  // ===== DOMESTIC VIOLENCE =====
  {
    name: 'Center for Family Justice - Crisis Services',
    organization: 'The Center for Family Justice',
    description: 'Connecticut\'s first Family Justice Center providing free, confidential, trauma-informed services for victims and survivors of domestic violence, sexual violence, human trafficking, and child abuse. Services include crisis counseling, safety planning, support groups, civil/legal advocacy, self-sufficiency services, and 24/7 crisis hotlines. Also operates Kathie\'s Place, a 15-bed emergency safe house for women and children fleeing abuse (up to 60 days).',
    categories: ['legal', 'mental-health', 'housing'],
    address: '753 Fairfield Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 334-6154',
    website: 'https://centerforfamilyjustice.org',
    hours: 'Walk-ins Mon-Fri 9am-4pm; DV Hotline 24/7: (888) 774-2900; Sexual Assault Hotline: (888) 999-5545',
    eligibility: {},
    howToApply: 'Walk in Mon-Fri 9am-4pm or call the 24/7 domestic violence hotline at (888) 774-2900. Sexual assault hotline (English): (888) 999-5545. En espanol: (888) 568-8332.',
    source: 'web-research'
  },

  // ===== SOBER LIVING / RECOVERY HOUSING =====
  {
    name: 'Gorham Fellowship Sober Living House',
    organization: 'The Gorham Fellowship Inc.',
    description: 'Structured sober living house for men in recovery. Provides a clean, safe environment with 24-hour house management, 9pm curfew, urine testing, addiction counseling, and IPO meetings. Located near Seaside Park and public transit. Costs: single room $620/mo, double room $500/mo, 4-person room $390/mo.',
    categories: ['housing', 'harm-reduction'],
    address: '1108 Fairfield Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 908-4487',
    website: 'http://www.gorhamfellowship.org',
    hours: 'Call for intake hours',
    eligibility: { ageMin: 18, populations: ['men'] },
    howToApply: 'Call (203) 908-4487 for availability and intake. Must be in recovery from substance use.',
    source: 'web-research'
  },
  {
    name: 'Recovery Community Development - Sober Living',
    organization: 'Recovery Community Development',
    description: 'Nonprofit operating CTARR-Certified Recovery Residences in Bridgeport. Purchases distressed properties and converts them into affordable sober living homes. Teaches home improvement trades to men in recovery. Rates $500-$1,500/month with need-based scholarships and "Work for Rent" programs available.',
    categories: ['housing', 'harm-reduction'],
    address: '925 Noble Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: null,
    website: 'https://www.recovcd.org',
    hours: 'Contact via website',
    eligibility: { ageMin: 18, populations: ['men'] },
    howToApply: 'Apply through recovcd.org. Scholarship and work-for-rent programs available for those who cannot afford full rate.',
    source: 'web-research'
  },
  {
    name: 'CASA Inc. - Noble House Transitional Housing',
    organization: 'CASA Inc.',
    description: 'Bilingual (English/Spanish) 16-bed, 24-hour transitional housing program for individuals in recovery. Average stay is 18 months but residents may stay longer if needed. Staff provide case management, referrals to treatment, support for permanent housing, and links to the recovering community.',
    categories: ['housing', 'harm-reduction'],
    address: '140 Noble Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 337-6529',
    website: 'https://www.casaincct.org/noble-house',
    hours: '24/7 residential program',
    eligibility: { ageMin: 18 },
    howToApply: 'Call (203) 337-6529 for intake. Bilingual services available in English and Spanish.',
    source: 'web-research'
  },

  // ===== YOUTH SERVICES =====
  {
    name: 'Bridgeport Lighthouse After-School Program',
    organization: 'City of Bridgeport Department of Youth Services',
    description: 'Free after-school program operating in 23 Bridgeport public schools, serving over 2,200 students daily. Programming includes academic enrichment, personal growth, social development, career readiness, arts, sports, and STEM activities. Runs from school dismissal to 5:30pm.',
    categories: ['childcare'],
    address: '700 Palisade Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06610',
    phone: '(203) 275-4601',
    website: 'https://www.bridgeportct.gov/government/departments/youth-services/lighthouse-program',
    hours: 'Mon-Fri, school dismissal to 5:30pm (school year)',
    eligibility: { populations: ['youth'] },
    howToApply: 'Contact (203) 275-4601 or email michele.dias@bridgeportct.gov. Programs at 23 school sites citywide.',
    source: 'web-research'
  },
  {
    name: 'Big Brothers Big Sisters of Southwestern CT',
    organization: 'Big Brothers Big Sisters of Southwestern CT',
    description: 'Youth mentoring program pairing children with adult mentors for one-on-one friendship and guidance. Community-based and site-based mentoring programs help youth build confidence, improve academic performance, and develop life skills.',
    categories: ['childcare'],
    address: '2470 Fairfield Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 366-3766',
    website: 'https://ctbigs.org',
    hours: 'Mon-Fri 9am-5pm (office)',
    eligibility: { populations: ['youth'] },
    howToApply: 'Call (203) 366-3766 or (800) 240-7186 to inquire about becoming a mentee or mentor.',
    source: 'web-research'
  },
  {
    name: 'Bridgeport Summer Youth Employment Program',
    organization: 'City of Bridgeport Department of Youth Services',
    description: 'Paid summer jobs for Bridgeport youth ages 14-21. Participants work 4 hours/day for approximately 5 weeks. Includes pre-employment training in job readiness, life skills, conflict resolution, and team building. Applications open May 1st annually.',
    categories: ['employment'],
    address: '700 Palisade Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06610',
    phone: '(203) 337-0184',
    website: 'https://www.bridgeportct.gov/government/departments/youth-services/summer-youth-employment',
    hours: 'Applications open May 1; program runs summer months',
    eligibility: { ageMin: 14, ageMax: 21, residencyRequired: true },
    howToApply: 'Apply online at bridgeportct.gov starting May 1. Must provide most recent report card and proof of Bridgeport residency.',
    source: 'web-research'
  },
  {
    name: 'Hall Neighborhood House - Youth Programs',
    organization: 'Hall Neighborhood House',
    description: 'After-school program on the East Side of Bridgeport offering homework help, educational activities, creative arts, social skill building, and mentoring from current college students. Also runs summer programs for school-age children and teenagers.',
    categories: ['childcare'],
    address: '52 George E. Pipkin Way',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 345-2000',
    website: 'https://hallneighborhoodhouse.org/youth-services/',
    hours: 'After school hours; call for schedule',
    eligibility: { populations: ['youth'] },
    howToApply: 'Call (203) 345-2000 or visit hallneighborhoodhouse.org to enroll.',
    source: 'web-research'
  },
  {
    name: 'Family ReEntry - Youth Mentoring & Reentry Services',
    organization: 'Family ReEntry',
    description: 'Evidence-based programs addressing behavioral health, domestic violence, reentry, and risks to youth. Services include youth mentoring, intensive case management, life skills training, abuse and mental health treatment, family interventions, psychoeducational groups, fatherhood engagement, and reentry housing assistance.',
    categories: ['mental-health', 'legal'],
    address: '75 Washington Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 838-0496',
    website: 'https://www.familyreentrycrj.org',
    hours: 'Mon-Fri; call for hours',
    eligibility: {},
    howToApply: 'Call (203) 838-0496 for intake and referral information.',
    source: 'web-research'
  },

  // ===== SENIOR SERVICES =====
  {
    name: 'Eisenhower Senior Center',
    organization: 'City of Bridgeport Department on Aging',
    description: 'City-operated senior center offering recreational activities, social programs, wellness activities, and congregate meals for Bridgeport seniors. Activities include arts and crafts, bingo, exercise classes, and special events.',
    categories: ['food', 'healthcare'],
    address: '307 Golden Hill Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 576-7993',
    website: 'https://www.bridgeportct.gov/government/departments/department-aging/eisenhower-senior-center',
    hours: 'Mon-Fri 8am-3pm',
    eligibility: { ageMin: 60 },
    howToApply: 'Walk in during operating hours. Open to Bridgeport seniors age 60+.',
    source: 'web-research'
  },
  {
    name: 'East Side Senior Center',
    organization: 'City of Bridgeport Department on Aging',
    description: 'Senior center on the East Side of Bridgeport offering engaging activities including dominoes, bingo, arts and crafts, fitness classes, and hot lunch. Provides a welcoming community space for older adults.',
    categories: ['food', 'healthcare'],
    address: '268 Putnam Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 332-4217',
    website: 'https://www.bridgeportct.gov/government/departments/department-aging/east-side-senior-center',
    hours: 'Mon-Fri 8am-3pm',
    eligibility: { ageMin: 60 },
    howToApply: 'Walk in during operating hours. Open to Bridgeport seniors age 60+.',
    source: 'web-research'
  },
  {
    name: 'CW Resources - Meals on Wheels (Bridgeport)',
    organization: 'CW Resources / RW Solutions',
    description: 'Home-delivered meals program for homebound seniors age 60+. Dietitian-certified nutritious meals providing one-third of daily recommended nutrients. Includes wellness checks during delivery. Funded through CT Home Care Program and Title III.',
    categories: ['food'],
    address: '215 Warren Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(860) 229-7700',
    website: 'https://www.cwresources.org/meals-on-wheels/',
    hours: 'Meals delivered Mon-Fri during daytime hours',
    eligibility: { ageMin: 60 },
    howToApply: 'Call (860) 229-7700 and ask for Meals on Wheels, or call SWCAA at (800) 994-9422 for referral.',
    source: 'web-research'
  },
  {
    name: 'SWCAA - Southwestern CT Agency on Aging',
    organization: 'Southwestern CT Agency on Aging',
    description: 'Regional Area Agency on Aging serving older adults and individuals with disabilities. Provides Medicare/Medicaid counseling, benefits screening, care management, long-term care planning, elder abuse prevention, and connections to home-delivered meals, senior day centers, home care, transportation, legal services, and nutrition programs. Call Aging Answers helpline for assistance.',
    categories: ['healthcare', 'legal', 'food', 'transportation'],
    address: '1000 Lafayette Boulevard',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 814-3698',
    website: 'https://swcaa.org',
    hours: 'Mon-Fri 8:30am-4:30pm; Aging Answers helpline: (800) 994-9422',
    eligibility: { ageMin: 60 },
    howToApply: 'Call Aging Answers at (800) 994-9422 for information and referrals, or visit the office.',
    source: 'web-research'
  },
  {
    name: 'Hall Neighborhood House - Senior Services',
    organization: 'Hall Neighborhood House',
    description: 'Comprehensive senior services on the East Side of Bridgeport including community meals, health screenings, caregiver supports, classes and workshops, social events, and advocacy. Helps seniors maintain independence and stay connected to their community.',
    categories: ['food', 'healthcare'],
    address: '52 George E. Pipkin Way',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 345-2000',
    website: 'https://hallneighborhoodhouse.org/senior-services/',
    hours: 'Mon-Fri; call for schedule',
    eligibility: { ageMin: 60 },
    howToApply: 'Call (203) 345-2000 or walk in to the center.',
    source: 'web-research'
  },

  // ===== DENTAL =====
  {
    name: 'Southwest Community Health Center - Dental Clinic',
    organization: 'Southwest Community Health Center',
    description: 'Comprehensive dental services for low-income and uninsured patients including preventive care, restorative care, extractions, and emergency dental. Sliding fee discount available for uninsured patients below 200% FPL. Also offers dental services on biweekly Saturdays.',
    categories: ['healthcare'],
    address: '46 Albion Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 334-3300',
    website: 'https://swchc.org/health-care-services/dental',
    hours: 'Mon/Wed/Fri 8:30am-4:30pm; Tue/Thu 8:30am-8pm; Bi-weekly Sat 9am-1pm',
    eligibility: { incomeLimitPctFpl: 200 },
    howToApply: 'Call (203) 334-3300 to schedule a dental appointment. Bring proof of income for sliding fee eligibility.',
    source: 'web-research'
  },
  {
    name: 'Optimus Health Care - Dental Services',
    organization: 'Optimus Health Care Inc.',
    description: 'Dental services for children and adults including emergency dental, preventive care, restorative care, x-rays, crowns, bridges, and partials. Sliding Fee Program available for patients without insurance based on income and family size.',
    categories: ['healthcare'],
    address: '982 East Main Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06608',
    phone: '(203) 696-3270',
    website: 'https://optimushealthcare.org',
    hours: 'Mon-Fri 8am-5pm; Tue extended hours until 7:30pm',
    eligibility: {},
    howToApply: 'Call (203) 696-3270 (dental line) to schedule. Accepts Medicaid, Medicare, and sliding scale for uninsured.',
    source: 'web-research'
  },

  // ===== EYE CARE / VISION =====
  {
    name: 'Vision To Learn - Free Student Eye Care',
    organization: 'Vision To Learn',
    description: 'Mobile vision clinic providing free eye exams and glasses to students K-12 in underserved schools. Over 9,000 Connecticut children served and 2,800 given free glasses. Mobile clinic visits Bridgeport public schools throughout the school year.',
    categories: ['healthcare'],
    address: null,
    city: 'Bridgeport',
    state: 'CT',
    zip: null,
    phone: null,
    website: 'https://visiontolearn.org/where-we-work/connecticut/',
    hours: 'Mobile clinic visits schools during school hours',
    eligibility: { populations: ['youth'] },
    howToApply: 'Screenings are conducted at participating Bridgeport public schools. Parents can ask their school nurse about Vision To Learn visits.',
    source: 'web-research'
  },

  // ===== COMMUNITY CENTERS / NEIGHBORHOOD ORGS =====
  {
    name: 'Burroughs Community Center',
    organization: 'Burroughs Community Center',
    description: 'Multi-service community center supporting over 75 local community groups and nonprofits, bringing 32,000+ people together annually. Programs include VITA free tax preparation, Our Woven Community refugee women\'s program, job readiness, financial stability, ESL, youth advocacy, and health/recreation activities.',
    categories: ['employment', 'immigration'],
    address: '2470 Fairfield Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 334-0293',
    website: 'https://burroughscenter.org',
    hours: 'Mon-Fri 9am-6pm',
    eligibility: {},
    howToApply: 'Walk in or call (203) 334-0293. Free VITA tax prep available Jan-April (call for appointment).',
    source: 'web-research'
  },

  // ===== EMPLOYMENT =====
  {
    name: 'Goodwill Career Center - Bridgeport',
    organization: 'Goodwill of Western & Northern Connecticut',
    description: 'Free career coaching services including one-on-one career counseling, resume writing, networking help, interview skills, access to local job postings, computer access, and weekly workshops. Registering makes you a "Goodwill Member for Life" with permanent access to support services.',
    categories: ['employment'],
    address: '165 Ocean Terrace',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 581-5040',
    website: 'https://www.gwct.org/locations/goodwill-bridgeport-career-center',
    hours: 'Mon-Fri 9:30am-4pm',
    eligibility: {},
    howToApply: 'Walk in during career center hours to register. All services are free.',
    source: 'web-research'
  },
  {
    name: 'The WorkPlace - Summer Youth Employment Program',
    organization: 'The WorkPlace Inc.',
    description: 'Paid summer work experience for young people ages 14-24 living in Bridgeport and surrounding communities. 20 hours weekly at minimum wage for up to 7 weeks. Includes job readiness training and work experience with local employers.',
    categories: ['employment'],
    address: '1000 Lafayette Blvd, Suite 501',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 610-8500',
    website: 'https://www.workplace.org',
    hours: 'Application period varies; program runs during summer',
    eligibility: { ageMin: 14, ageMax: 24 },
    howToApply: 'Apply online at workplace.org. Applications accepted exclusively online. Check website for application period.',
    source: 'web-research'
  },

  // ===== HOUSING =====
  {
    name: 'Building Neighborhoods Together - Housing Services',
    organization: 'Building Neighborhoods Together',
    description: 'Fairfield County\'s most active nonprofit affordable housing developer. Owns and manages 230+ units. Services include pre-purchase education, rental assistance counseling, eviction and foreclosure prevention, credit repair, fair housing assistance, financial literacy workshops for youth, and reverse mortgage counseling for seniors.',
    categories: ['housing', 'legal'],
    address: '999 Broad Street, Suite 410',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 362-1085',
    website: 'https://www.bntweb.org',
    hours: 'Mon-Fri; call for hours',
    eligibility: {},
    howToApply: 'Call (203) 362-1085 or visit bntweb.org for housing counseling and program information.',
    source: 'web-research'
  },

  // ===== HEALTHCARE — WIC =====
  {
    name: 'WIC Program - Optimus Health Care',
    organization: 'Optimus Health Care Inc.',
    description: 'Women, Infants and Children (WIC) supplemental nutrition program providing healthy foods, nutrition education, breastfeeding support, and health care referrals for pregnant/postpartum women, infants, and children up to age 5 at nutritional risk.',
    categories: ['food', 'healthcare'],
    address: '1450 Barnum Avenue, Suite 205',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06610',
    phone: '(203) 333-9200',
    website: 'https://optimushealthcare.org/services/programs/the-wic-program/',
    hours: 'Call to confirm hours and schedule appointment',
    eligibility: { incomeLimitPctFpl: 185, populations: ['women', 'families'] },
    howToApply: 'Call (203) 333-9200 to schedule an appointment. Must be pregnant, postpartum, breastfeeding, or have children under 5.',
    source: 'web-research'
  },

  // ===== MENTAL HEALTH — CHILDREN =====
  {
    name: 'Child & Family Guidance Center',
    organization: 'The Child & Family Guidance Center Inc.',
    description: 'Culturally-informed mental health care for children ages 0-18 and their families since 1925. Outpatient clinic providing individual, family, and group therapy, psychiatric evaluation, and medication management for children experiencing emotional and behavioral problems. Regardless of ability to pay.',
    categories: ['mental-health'],
    address: '180 Fairfield Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 394-6529',
    website: 'https://cfguidance.com',
    hours: 'Mon-Fri; call for hours',
    eligibility: { ageMax: 18 },
    howToApply: 'Call (203) 394-6529 for intake. No one turned away for inability to pay.',
    source: 'web-research'
  },

  // ===== IMMIGRATION =====
  {
    name: 'Catholic Charities - Immigration Services',
    organization: 'Catholic Charities of Fairfield County',
    description: 'Immigration legal services specializing in citizenship applications and family-based petitions for individuals seeking legal status and family reunification. Multi-lingual staff (English, Spanish, French). Initial consultation fee $75 per case.',
    categories: ['immigration', 'legal'],
    address: '1406 State Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 416-1322',
    website: 'https://www.ccfairfield.org/project/immigration/',
    hours: 'Mon-Fri; call for hours',
    eligibility: {},
    howToApply: 'Call (203) 416-1322 or email CCFC-ImmigrationOffice@ccfc-ct.org. $75 initial consultation fee.',
    source: 'web-research'
  },

  // ===== VETERANS =====
  {
    name: 'Bridgeport Veterans Affairs Office',
    organization: 'City of Bridgeport',
    description: 'City veterans affairs office providing information, referrals, and direct services to Bridgeport veterans. Includes a food pantry on the 3rd Tuesday and Wednesday of each month (10am-2pm), connections to VA benefits, and coordination of the free VA Hospital shuttle service.',
    categories: ['food', 'healthcare'],
    address: '20 Thorme Street',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 576-8348',
    website: 'https://www.bridgeportct.gov/government/departments/health-social-services/veterans-affairs',
    hours: 'Mon-Fri 9am-4:30pm; Food pantry: 3rd Tue & Wed 10am-2pm',
    eligibility: { populations: ['veterans'] },
    howToApply: 'Walk in or call (203) 576-8348. Open to Bridgeport veterans.',
    source: 'web-research'
  },

  // ===== DIAPER BANK / BABY SUPPLIES =====
  {
    name: 'Alliance for Community Empowerment - Diaper Bank',
    organization: 'Alliance for Community Empowerment',
    description: 'Free diapers, period products, and adult incontinence products for families in need through partnership with The Diaper Bank of Connecticut. Two pickup locations in Bridgeport.',
    categories: ['childcare'],
    address: '816 Fairfield Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 366-8241 ext. 3220',
    website: 'https://thediaperbank.org',
    hours: 'Mon-Fri; call for pickup schedule',
    eligibility: { populations: ['families'] },
    howToApply: 'Call Francis Kalangala at (203) 366-8241 ext. 3220 for enrollment. Also available at 1070 Park Ave.',
    source: 'web-research'
  },

  // ===== LEGAL — COURTS =====
  {
    name: 'Bridgeport Probate Court',
    organization: 'Connecticut Probate Courts',
    description: 'Handles matters including wills and estates, conservatorships, guardianship of minors, name changes, adoption, and commitment proceedings. Public court serving Bridgeport residents.',
    categories: ['legal'],
    address: '999 Broad Street (Government Center)',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 576-3945',
    website: 'https://www.ctprobate.gov/courts/bridgeport-probate-court',
    hours: 'Mon-Thu 8:30am-5pm; Fri 8:30am-4pm',
    eligibility: {},
    howToApply: 'Visit the court during business hours or call (203) 576-3945. Many forms available at ctprobate.gov.',
    source: 'web-research'
  },

  // ===== CATHOLIC CHARITIES PROGRAMS =====
  {
    name: 'Catholic Charities - Morning Glory Breakfast & Thomas Merton Meals',
    organization: 'Catholic Charities of Fairfield County',
    description: 'Hot meal programs serving up to 300 meals daily at the Thomas Merton Center. Morning Glory Breakfast Kitchen serves breakfast and the center provides lunch. Also offers SNAP outreach and engagement to help eligible residents apply for food stamps.',
    categories: ['food'],
    address: '43 Madison Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06604',
    phone: '(203) 416-1503',
    website: 'https://www.ccfairfield.org',
    hours: 'Call for meal service hours',
    eligibility: {},
    howToApply: 'Walk in for meals. No requirements except mutual respect and dignity.',
    source: 'web-research'
  },
  {
    name: 'Catholic Charities - Room to Grow Preschool',
    organization: 'Catholic Charities of Fairfield County',
    description: 'State-licensed and nationally accredited preschool funded by Early Start CT. Provides high-quality care and early education for children ages 3-5 from local communities. Multi-lingual staff.',
    categories: ['childcare'],
    address: '238 Jewett Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06606',
    phone: '(203) 416-1503',
    website: 'https://www.ccfairfield.org',
    hours: 'School year hours; call for details',
    eligibility: { populations: ['families'] },
    howToApply: 'Call (203) 416-1503 to inquire about enrollment and eligibility.',
    source: 'web-research'
  },

  // ===== DISABILITY SERVICES =====
  {
    name: 'The Kennedy Collective - Disability Employment Services',
    organization: 'The Kennedy Collective',
    description: 'Job placement and workforce development for people with disabilities. Operates the Kennedy Collective Placement Program and Mental Health Work Services Program (funded by DMHAS). Works with GBCMHC and LifeBridge in Bridgeport. Also provides day programs, residential support, and transition services.',
    categories: ['employment'],
    address: '2440 Reservoir Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06606',
    phone: '(203) 365-8522',
    website: 'https://www.thekennedycollective.org',
    hours: 'Mon-Fri; call for hours',
    eligibility: {},
    howToApply: 'Call (203) 365-8522 or visit thekennedycollective.org for program information and referral.',
    source: 'web-research'
  },

  // ===== CLOTHING / BASIC NEEDS =====
  {
    name: 'Bridgeport Rescue Mission - Clothing Center',
    organization: 'Bridgeport Rescue Mission',
    description: 'Free clothing distribution for children, men, and women. Primarily serves individuals experiencing homelessness, though very low-income residents may also qualify. Part of the Rescue Mission\'s comprehensive services.',
    categories: ['housing'],
    address: '1088 Fairfield Avenue',
    city: 'Bridgeport',
    state: 'CT',
    zip: '06605',
    phone: '(203) 333-4087',
    website: 'https://bridgeportrescuemission.org/clothing/',
    hours: 'Call for current hours',
    eligibility: { housingStatus: ['homeless', 'at_risk'] },
    howToApply: 'Walk in or call (203) 333-4087 for availability.',
    source: 'web-research'
  },
]
